name: Build APP
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v1

    - name: Fix DirectStore for IE11
      uses: jacobtomlinson/gha-find-replace@master

      with:
        find: "'vue-i18n'"
        replace: "'vue-i18n/dist/vue-i18n.esm.js'"

    - name: Build Vue.js application
      run: |
        npm install
        npm run build
    - name: Commit files
      run: |
          cd dist
          git init
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add --force -A
          git commit -m "Publish page"
    - name: Push to production
      uses: ad-m/github-push-action@master
      with:
       github_token: ${{ secrets.GITHUB_TOKEN }}
       branch: gh-pages
       force: true
       directory: dist

