name: Build APP
on:
  push:
    branches:
      - master 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v1

    - name: Build Vue.js application
      run: |
        npm install
        npm run build
        
    - name: Push to production
      run: |
        cd dist
        git init
        git add -A
        git commit -m 'deploy' 
        git push -f git@github.com:HamAndRock/havelka.net.git production
        
