name: Build APP
on:
  push:
    branches:
      - master 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v1

    - name: Build Vue.js application
      run: |
        npm install
        npm run build
        
    - name: Push to production
      uses: johno/actions-push-subdirectories@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        args: dist HamAndRock
        
